const products = [
  {
    _id: 1,
    name: "Animal Crossing Stickers",
    image: "/assets/productImages/acStickers.jpg",
    description: "Hand-drawn stickers inspired by Animal Crossing",
    vendorName: "handxmade",
    category: "Stickers",
    price: 5,
    quantity: 10,
    reviewRating: 4.5,
  },
  {
    _id: 2,
    name: "Bread Sticker Pack",
    image: "/assets/productImages/breadStickers.jpg",
    description: "Delicious bread-themed stickers for your collection",
    vendorName: "handxmade",
    category: "Stickers",
    price: 3.99,
    quantity: 7,
    reviewRating: 4.0,
  },
  {
    _id: 3,
    name: "Time To Celebrate Sticker Pack",
    image: "/assets/productImages/celebrateStickers.jpg",
    description: "Celebrate special moments with these festive stickers",
    vendorName: "handxmade",
    category: "Stickers",
    price: 4.99,
    quantity: 5,
    reviewRating: 3.2,
  },
  {
    _id: 4,
    name: "Digital Sticker Pack",
    image: "/assets/productImages/digitalStickers.jpg",
    description: "A collection of digital-themed stickers for your devices",
    vendorName: "handxmade",
    category: "Stickers",
    price: 2.99,
    quantity: 11,
    reviewRating: 4.8,
  },
  {
    _id: 5,
    name: "Sunflower Hair Pin",
    image: "/assets/productImages/flowerPin.jpg",
    description: "Elegant sunflower hairpin for a stylish look",
    vendorName: "handfully",
    category: "Accessories",
    price: 19.99,
    quantity: 7,
    reviewRating: 4.2,
  },
  {
    _id: 6,
    name: "Sakura Flower Ring",
    image: "/assets/productImages/flowerRing.jpg",
    description: "Beautiful sakura flower ring for a touch of nature",
    vendorName: "handfully",
    category: "Accessories",
    price: 14.99,
    quantity: 0,
    reviewRating: 4.5,
  },
  {
    _id: 7,
    name: "Sakura Flower Ear Stud",
    image: "/assets/productImages/flowerStud.jpg",
    description: "Charming sakura flower ear stud for an elegant look",
    vendorName: "handfully",
    category: "Accessories",
    price: 14.99,
    quantity: 0,
    reviewRating: 4.3,
  },
  {
    _id: 8,
    name: "Our Hawker Generation Stickers",
    image: "/assets/productImages/hawkerStickers.jpg",
    description: "Stickers celebrating the hawker culture",
    vendorName: "handfully",
    category: "Stickers",
    price: 3.49,
    quantity: 0,
    reviewRating: 4.1,
  },
  {
    _id: 9,
    name: "Rainbow Earrings",
    image: "/assets/productImages/rainbowEarrings.jpg",
    description: "Vibrant rainbow earrings to brighten your day",
    vendorName: "handfully",
    category: "Accessories",
    price: 9.99,
    quantity: 0,
    reviewRating: 4.7,
  },
];

export default products;
