const store = [
  {
    _id: "1",
    storeName: "handxmade",
    storeImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/handxmadeLogo.png?raw=true",
    storeFrontImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/storeHandxmade.png?raw=true",
    products: [
      {
        _id: 1,
        name: "Animal Crossing Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1590476871987-HLSRP6S3D3X29P1XDV86/P1240396.jpg?format=1500w",
        description: "Hand-drawn stickers inspired by Animal Crossing",
        vendorName: "handxmade",
        category: "Stickers",
        price: 5,
        quantity: 10,
        reviewRating: 4.5,
      },
      {
        _id: 2,
        name: "Bread Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1603531705536-GV2AN2NHDDCHPRH0JW4S/P1250375.jpg?format=1500w",
        description: "Delicious bread-themed stickers for your collection",
        vendorName: "handxmade",
        category: "Stickers",
        price: 3.99,
        quantity: 7,
        reviewRating: 4.0,
      },
      {
        _id: 3,
        name: "Time To Celebrate Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1614850198307-LT6L0HSG4K4GLSY97RA9/P1260318.jpg?format=1500w",
        description: "Celebrate special moments with these festive stickers",
        vendorName: "handxmade",
        category: "Stickers",
        price: 4.99,
        quantity: 5,
        reviewRating: 3.2,
      },
      {
        _id: 4,
        name: "Digital Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1600686229919-UYD8EG6X8VP61SGSKNPU/P1250193+1-1.jpg?format=1500w",
        description: "A collection of digital-themed stickers for your devices",
        vendorName: "handxmade",
        category: "Stickers",
        price: 2.99,
        quantity: 11,
        reviewRating: 4.8,
      },
      {
        _id: 5,
        name: "Sunflower Hair Pin",
        image:
          "https://www.handfully.com/cdn/shop/files/image_900x.jpg?v=1682434022",
        description: "Elegant sunflower hairpin for a stylish look",
        vendorName: "handfully",
        category: "Accessories",
        price: 19.99,
        quantity: 7,
        reviewRating: 4.2,
      },
      {
        _id: 6,
        name: "Sakura Flower Ring",
        image:
          "https://www.handfully.com/cdn/shop/products/image_7b99de56-67e8-438d-8e00-08682ad5d0be_900x.jpg?v=1682163485",
        description: "Beautiful sakura flower ring for a touch of nature",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.5,
      },
      {
        _id: 7,
        name: "Sakura Flower Ear Stud",
        image:
          "https://www.handfully.com/cdn/shop/files/image_c7817592-f3bc-49a9-adf0-e6a028cab57f_1024x1024@2x.jpg?v=1688720781",
        description: "Charming sakura flower ear stud for an elegant look",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.3,
      },
      {
        _id: 8,
        name: "Our Hawker Generation Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1553280098798-XINLBD55FOWYEXW4I9I8/P1170291+copy.jpg?format=1500w",
        description: "Stickers celebrating the hawker culture",
        vendorName: "handfully",
        category: "Stickers",
        price: 3.49,
        quantity: 0,
        reviewRating: 4.1,
      },
      {
        _id: 9,
        name: "Rainbow Earrings",
        image:
          "https://www.handfully.com/cdn/shop/files/image_5cea19a2-deed-447f-a2e1-173cb451a075_1024x1024@2x.jpg?v=1686143498",
        description: "Vibrant rainbow earrings to brighten your day",
        vendorName: "handfully",
        category: "Accessories",
        price: 9.99,
        quantity: 0,
        reviewRating: 4.7,
      },
    ],
  },
  {
    _id: "2",
    storeName: "handfully",
    storeImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/handfullyLogo.png?raw=true",
    storeFrontImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/storeHandfully.png?raw=true",
    products: [
      {
        _id: 1,
        name: "Animal Crossing Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1590476871987-HLSRP6S3D3X29P1XDV86/P1240396.jpg?format=1500w",
        description: "Hand-drawn stickers inspired by Animal Crossing",
        vendorName: "handxmade",
        category: "Stickers",
        price: 5,
        quantity: 10,
        reviewRating: 4.5,
      },
      {
        _id: 2,
        name: "Bread Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1603531705536-GV2AN2NHDDCHPRH0JW4S/P1250375.jpg?format=1500w",
        description: "Delicious bread-themed stickers for your collection",
        vendorName: "handxmade",
        category: "Stickers",
        price: 3.99,
        quantity: 7,
        reviewRating: 4.0,
      },
      {
        _id: 3,
        name: "Time To Celebrate Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1614850198307-LT6L0HSG4K4GLSY97RA9/P1260318.jpg?format=1500w",
        description: "Celebrate special moments with these festive stickers",
        vendorName: "handxmade",
        category: "Stickers",
        price: 4.99,
        quantity: 5,
        reviewRating: 3.2,
      },
      {
        _id: 4,
        name: "Digital Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1600686229919-UYD8EG6X8VP61SGSKNPU/P1250193+1-1.jpg?format=1500w",
        description: "A collection of digital-themed stickers for your devices",
        vendorName: "handxmade",
        category: "Stickers",
        price: 2.99,
        quantity: 11,
        reviewRating: 4.8,
      },
      {
        _id: 5,
        name: "Sunflower Hair Pin",
        image:
          "https://www.handfully.com/cdn/shop/files/image_900x.jpg?v=1682434022",
        description: "Elegant sunflower hairpin for a stylish look",
        vendorName: "handfully",
        category: "Accessories",
        price: 19.99,
        quantity: 7,
        reviewRating: 4.2,
      },
      {
        _id: 6,
        name: "Sakura Flower Ring",
        image:
          "https://www.handfully.com/cdn/shop/products/image_7b99de56-67e8-438d-8e00-08682ad5d0be_900x.jpg?v=1682163485",
        description: "Beautiful sakura flower ring for a touch of nature",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.5,
      },
      {
        _id: 7,
        name: "Sakura Flower Ear Stud",
        image:
          "https://www.handfully.com/cdn/shop/files/image_c7817592-f3bc-49a9-adf0-e6a028cab57f_1024x1024@2x.jpg?v=1688720781",
        description: "Charming sakura flower ear stud for an elegant look",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.3,
      },
      {
        _id: 8,
        name: "Our Hawker Generation Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1553280098798-XINLBD55FOWYEXW4I9I8/P1170291+copy.jpg?format=1500w",
        description: "Stickers celebrating the hawker culture",
        vendorName: "handfully",
        category: "Stickers",
        price: 3.49,
        quantity: 0,
        reviewRating: 4.1,
      },
      {
        _id: 9,
        name: "Rainbow Earrings",
        image:
          "https://www.handfully.com/cdn/shop/files/image_5cea19a2-deed-447f-a2e1-173cb451a075_1024x1024@2x.jpg?v=1686143498",
        description: "Vibrant rainbow earrings to brighten your day",
        vendorName: "handfully",
        category: "Accessories",
        price: 9.99,
        quantity: 0,
        reviewRating: 4.7,
      },
    ],
  },
  {
    _id: "3",
    storeName: "My Store 3",
    storeImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/wheniwasfourLogo.png?raw=true",
    storeFrontImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/storeWheniwasfour.png?raw=true",
    products: [
      {
        _id: 1,
        name: "Animal Crossing Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1590476871987-HLSRP6S3D3X29P1XDV86/P1240396.jpg?format=1500w",
        description: "Hand-drawn stickers inspired by Animal Crossing",
        vendorName: "handxmade",
        category: "Stickers",
        price: 5,
        quantity: 10,
        reviewRating: 4.5,
      },
      {
        _id: 2,
        name: "Bread Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1603531705536-GV2AN2NHDDCHPRH0JW4S/P1250375.jpg?format=1500w",
        description: "Delicious bread-themed stickers for your collection",
        vendorName: "handxmade",
        category: "Stickers",
        price: 3.99,
        quantity: 7,
        reviewRating: 4.0,
      },
      {
        _id: 3,
        name: "Time To Celebrate Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1614850198307-LT6L0HSG4K4GLSY97RA9/P1260318.jpg?format=1500w",
        description: "Celebrate special moments with these festive stickers",
        vendorName: "handxmade",
        category: "Stickers",
        price: 4.99,
        quantity: 5,
        reviewRating: 3.2,
      },
      {
        _id: 4,
        name: "Digital Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1600686229919-UYD8EG6X8VP61SGSKNPU/P1250193+1-1.jpg?format=1500w",
        description: "A collection of digital-themed stickers for your devices",
        vendorName: "handxmade",
        category: "Stickers",
        price: 2.99,
        quantity: 11,
        reviewRating: 4.8,
      },
      {
        _id: 5,
        name: "Sunflower Hair Pin",
        image:
          "https://www.handfully.com/cdn/shop/files/image_900x.jpg?v=1682434022",
        description: "Elegant sunflower hairpin for a stylish look",
        vendorName: "handfully",
        category: "Accessories",
        price: 19.99,
        quantity: 7,
        reviewRating: 4.2,
      },
      {
        _id: 6,
        name: "Sakura Flower Ring",
        image:
          "https://www.handfully.com/cdn/shop/products/image_7b99de56-67e8-438d-8e00-08682ad5d0be_900x.jpg?v=1682163485",
        description: "Beautiful sakura flower ring for a touch of nature",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.5,
      },
      {
        _id: 7,
        name: "Sakura Flower Ear Stud",
        image:
          "https://www.handfully.com/cdn/shop/files/image_c7817592-f3bc-49a9-adf0-e6a028cab57f_1024x1024@2x.jpg?v=1688720781",
        description: "Charming sakura flower ear stud for an elegant look",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.3,
      },
      {
        _id: 8,
        name: "Our Hawker Generation Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1553280098798-XINLBD55FOWYEXW4I9I8/P1170291+copy.jpg?format=1500w",
        description: "Stickers celebrating the hawker culture",
        vendorName: "handfully",
        category: "Stickers",
        price: 3.49,
        quantity: 0,
        reviewRating: 4.1,
      },
      {
        _id: 9,
        name: "Rainbow Earrings",
        image:
          "https://www.handfully.com/cdn/shop/files/image_5cea19a2-deed-447f-a2e1-173cb451a075_1024x1024@2x.jpg?v=1686143498",
        description: "Vibrant rainbow earrings to brighten your day",
        vendorName: "handfully",
        category: "Accessories",
        price: 9.99,
        quantity: 0,
        reviewRating: 4.7,
      },
    ],
  },
  {
    _id: "4",
    storeName: "My Store 4",
    storeImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/tinysupplyLogo.png?raw=true",
    storeFrontImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/storeTinySupply.png?raw=true",
    products: [
      {
        _id: 1,
        name: "Animal Crossing Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1590476871987-HLSRP6S3D3X29P1XDV86/P1240396.jpg?format=1500w",
        description: "Hand-drawn stickers inspired by Animal Crossing",
        vendorName: "handxmade",
        category: "Stickers",
        price: 5,
        quantity: 10,
        reviewRating: 4.5,
      },
      {
        _id: 2,
        name: "Bread Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1603531705536-GV2AN2NHDDCHPRH0JW4S/P1250375.jpg?format=1500w",
        description: "Delicious bread-themed stickers for your collection",
        vendorName: "handxmade",
        category: "Stickers",
        price: 3.99,
        quantity: 7,
        reviewRating: 4.0,
      },
      {
        _id: 3,
        name: "Time To Celebrate Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1614850198307-LT6L0HSG4K4GLSY97RA9/P1260318.jpg?format=1500w",
        description: "Celebrate special moments with these festive stickers",
        vendorName: "handxmade",
        category: "Stickers",
        price: 4.99,
        quantity: 5,
        reviewRating: 3.2,
      },
      {
        _id: 4,
        name: "Digital Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1600686229919-UYD8EG6X8VP61SGSKNPU/P1250193+1-1.jpg?format=1500w",
        description: "A collection of digital-themed stickers for your devices",
        vendorName: "handxmade",
        category: "Stickers",
        price: 2.99,
        quantity: 11,
        reviewRating: 4.8,
      },
      {
        _id: 5,
        name: "Sunflower Hair Pin",
        image:
          "https://www.handfully.com/cdn/shop/files/image_900x.jpg?v=1682434022",
        description: "Elegant sunflower hairpin for a stylish look",
        vendorName: "handfully",
        category: "Accessories",
        price: 19.99,
        quantity: 7,
        reviewRating: 4.2,
      },
      {
        _id: 6,
        name: "Sakura Flower Ring",
        image:
          "https://www.handfully.com/cdn/shop/products/image_7b99de56-67e8-438d-8e00-08682ad5d0be_900x.jpg?v=1682163485",
        description: "Beautiful sakura flower ring for a touch of nature",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.5,
      },
      {
        _id: 7,
        name: "Sakura Flower Ear Stud",
        image:
          "https://www.handfully.com/cdn/shop/files/image_c7817592-f3bc-49a9-adf0-e6a028cab57f_1024x1024@2x.jpg?v=1688720781",
        description: "Charming sakura flower ear stud for an elegant look",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.3,
      },
      {
        _id: 8,
        name: "Our Hawker Generation Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1553280098798-XINLBD55FOWYEXW4I9I8/P1170291+copy.jpg?format=1500w",
        description: "Stickers celebrating the hawker culture",
        vendorName: "handfully",
        category: "Stickers",
        price: 3.49,
        quantity: 0,
        reviewRating: 4.1,
      },
      {
        _id: 9,
        name: "Rainbow Earrings",
        image:
          "https://www.handfully.com/cdn/shop/files/image_5cea19a2-deed-447f-a2e1-173cb451a075_1024x1024@2x.jpg?v=1686143498",
        description: "Vibrant rainbow earrings to brighten your day",
        vendorName: "handfully",
        category: "Accessories",
        price: 9.99,
        quantity: 0,
        reviewRating: 4.7,
      },
    ],
  },
  {
    _id: "5",
    storeName: "My Store 5",
    storeImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/tinysupplyLogo.png?raw=true",
    storeFrontImage:
      "https://github.com/caiyinn/the-local-choice/blob/main/frontend/src/assets/allStoresImages/storeTinySupply.png?raw=true",
    products: [
      {
        _id: 1,
        name: "Animal Crossing Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1590476871987-HLSRP6S3D3X29P1XDV86/P1240396.jpg?format=1500w",
        description: "Hand-drawn stickers inspired by Animal Crossing",
        vendorName: "handxmade",
        category: "Stickers",
        price: 5,
        quantity: 10,
        reviewRating: 4.5,
      },
      {
        _id: 2,
        name: "Bread Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1603531705536-GV2AN2NHDDCHPRH0JW4S/P1250375.jpg?format=1500w",
        description: "Delicious bread-themed stickers for your collection",
        vendorName: "handxmade",
        category: "Stickers",
        price: 3.99,
        quantity: 7,
        reviewRating: 4.0,
      },
      {
        _id: 3,
        name: "Time To Celebrate Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1614850198307-LT6L0HSG4K4GLSY97RA9/P1260318.jpg?format=1500w",
        description: "Celebrate special moments with these festive stickers",
        vendorName: "handxmade",
        category: "Stickers",
        price: 4.99,
        quantity: 5,
        reviewRating: 3.2,
      },
      {
        _id: 4,
        name: "Digital Sticker Pack",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1600686229919-UYD8EG6X8VP61SGSKNPU/P1250193+1-1.jpg?format=1500w",
        description: "A collection of digital-themed stickers for your devices",
        vendorName: "handxmade",
        category: "Stickers",
        price: 2.99,
        quantity: 11,
        reviewRating: 4.8,
      },
      {
        _id: 5,
        name: "Sunflower Hair Pin",
        image:
          "https://www.handfully.com/cdn/shop/files/image_900x.jpg?v=1682434022",
        description: "Elegant sunflower hairpin for a stylish look",
        vendorName: "handfully",
        category: "Accessories",
        price: 19.99,
        quantity: 7,
        reviewRating: 4.2,
      },
      {
        _id: 6,
        name: "Sakura Flower Ring",
        image:
          "https://www.handfully.com/cdn/shop/products/image_7b99de56-67e8-438d-8e00-08682ad5d0be_900x.jpg?v=1682163485",
        description: "Beautiful sakura flower ring for a touch of nature",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.5,
      },
      {
        _id: 7,
        name: "Sakura Flower Ear Stud",
        image:
          "https://www.handfully.com/cdn/shop/files/image_c7817592-f3bc-49a9-adf0-e6a028cab57f_1024x1024@2x.jpg?v=1688720781",
        description: "Charming sakura flower ear stud for an elegant look",
        vendorName: "handfully",
        category: "Accessories",
        price: 14.99,
        quantity: 0,
        reviewRating: 4.3,
      },
      {
        _id: 8,
        name: "Our Hawker Generation Stickers",
        image:
          "https://images.squarespace-cdn.com/content/v1/561debf1e4b08aeed3fd59c8/1553280098798-XINLBD55FOWYEXW4I9I8/P1170291+copy.jpg?format=1500w",
        description: "Stickers celebrating the hawker culture",
        vendorName: "handfully",
        category: "Stickers",
        price: 3.49,
        quantity: 0,
        reviewRating: 4.1,
      },
      {
        _id: 9,
        name: "Rainbow Earrings",
        image:
          "https://www.handfully.com/cdn/shop/files/image_5cea19a2-deed-447f-a2e1-173cb451a075_1024x1024@2x.jpg?v=1686143498",
        description: "Vibrant rainbow earrings to brighten your day",
        vendorName: "handfully",
        category: "Accessories",
        price: 9.99,
        quantity: 0,
        reviewRating: 4.7,
      },
    ],
  },
];

export default store;
